# ThreatHunting
Repository dedicated for threat hunting tools &amp; scripts

| Name               | Type                | Description                                                                                                                                                                                                                                                                  | Link                                                              |
|--------------------|---------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------|
| APT-Hunter         | Event Log Hunting   | APT-Hunter is Threat Hunting tool for windows event logs which made by purple team mindset to provide detect APT movements hidden in the sea of windows event logs to decrease the time to uncover suspicious activity                                                       | https://github.com/ahmedkhlief/APT-Hunter                         |
| Autoruns           | Persistence Hunting | Autoruns is a Microsoft tool that identifies software configured to run when a device is booted, or a user logs into their account.                                                                                                                                          | https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns |
| Binlex             | Malware Hunting     | A Binary Genetic Traits Lexer Framework                                                                                                                                                                                                                                      | https://github.com/c3rb3ru5d3d53c/binlex                          |
| CAPA               | Malware Hunting     | The FLARE team's open-source tool to identify capabilities in executable files.                                                                                                                                                                                              | https://github.com/mandiant/capa                                  |
| Chainsaw           | Event Log Hunting   | Rapidly Search and Hunt through Windows Forensic Artefacts                                                                                                                                                                                                                   | https://github.com/WithSecureLabs/chainsaw                        |
| CimSweep           | Remote Hunting      | CimSweep is a suite of CIM/WMI-based tools that enable the ability to perform incident response and hunting operations remotely across all versions of Windows.                                                                                                              | https://github.com/mattifestation/CimSweep                        |
| CobaltStrikeScan   | Memory Hunting      | Scan files or process memory for CobaltStrike beacons and parse their configuration                                                                                                                                                                                          | https://github.com/Apr4h/CobaltStrikeScan                         |
| DeepBlueCLI        | Event Log Hunting   | PowerShell Module for Threat Hunting via Windows Event Logs                                                                                                                                                                                                                  | https://github.com/sans-blue-team/DeepBlueCLI                     |
| DensityScout       | Malware Hunting     | This tool calculates density (like entropy) for files of any file-system-path to finally output an accordingly descending ordered list. This makes it possible to quickly find (even unknown) malware on a potentially infected Microsoft Windows driven machine.            | https://cert.at/en/downloads/software/software-densityscout       |
| GMER               | Rootkit Hunting     | GMER is an application that detects and removes rootkits                                                                                                                                                                                                                     | http://www.gmer.net/?m=0                                          |
| HELK (Hunting ELK) | Hunting Framework   | The Hunting ELK or simply the HELK is one of the first open source hunt platforms with advanced analytics capabilities such as SQL declarative language, graphing, structured streaming, and even machine learning via Jupyter notebooks and Apache Spark over an ELK stack. | https://github.com/Cyb3rWard0g/HELK                               |
| Hollows_Hunter     | Memory Hunting      | Scans all running processes. Recognizes and dumps a variety of potentially malicious implants (replaced/implanted PEs, shellcodes, hooks, in-memory patches).                                                                                                                | https://github.com/hasherezade/hollows_hunter                     |
| Oriana             | Event Log Hunting   | Oriana is a threat hunting tool that leverages a subset of Windows events to build relationships, calculate totals and run analytics. The results are presented in a Web layer to help defenders identify outliers and suspicious behavior on corporate environments.        | https://github.com/mvelazc0/Oriana                                |
| PE-Sieve           | Memory Hunting      | Scans a given process. Recognizes and dumps a variety of potentially malicious implants (replaced/injected PEs, shellcodes, hooks, in-memory patches).                                                                                                                       | https://github.com/hasherezade/pe-sieve                           |
| PSHunt             | General Hunting     | Powershell Threat Hunting Module                                                                                                                                                                                                                                             | https://github.com/Infocyte/PSHunt                                |
| RedHunt-OS         | Hunting Framework   | Virtual Machine for Adversary Emulation and Threat Hunting                                                                                                                                                                                                                   | https://github.com/redhuntlabs/RedHunt-OS                         |
| Reg_Hunter         | Registry Hunting    | Blueteam operational triage registry hunting/forensic tool.                                                                                                                                                                                                                  | https://github.com/theflakes/reg_hunter                           |
| RegLister          | Registry Hunting    | Recurse through a registry, identifying values with large data -- a registry malware hunter                                                                                                                                                                                  | https://github.com/dnlongen/RegLister                             |
| RkHunter           | Rootkit Hunting     | Rkhunter is a Unix-based tool that scans for rootkits, backdoors and possible local exploits.                                                                                                                                                                                | https://github.com/installation/rkhunter                          |
| SecurityOnion      | Hunting Framework   | Security Onion 2 - Linux distro for threat hunting, enterprise security monitoring, and log management                                                                                                                                                                       | https://github.com/Security-Onion-Solutions/securityonion/        |
| Sentinel-Attack    | Hunting Framework   | Tools to rapidly deploy a threat hunting capability on Azure Sentinel that leverages Sysmon and MITRE ATT&CK                                                                                                                                                                 | https://github.com/BlueTeamLabs/sentinel-attack                   |
| SQHunter           | Hunting Framework   | A simple threat hunting tool based on osquery, Salt Open and Cymon API                                                                                                                                                                                                       | https://github.com/0x4D31/sqhunter                                |
| Suveyor            | Baseline Hunting    | Surveyor is a Python utility that queries Endpoint Detection and Response (EDR) products and summarizes the results.                                                                                                                                                         | https://github.com/redcanaryco/surveyor                           |
| YARA               | Malware Hunting     | The pattern matching swiss knife                                                                                                                                                                                                                                             | https://github.com/virustotal/yara                                |
